"""MyrtDesk backlight constants"""

DOMAIN_BACKLIGHT = 1

COMMAND_READ_STATE = 0
COMMAND_SET_EFFECT = 1
COMMAND_SET_EFFECT_DATA = 2
COMMAND_SET_COLOR = 3
COMMAND_SET_WHITE = 4
COMMAND_SET_BRIGHTNESS = 5
COMMAND_TURN_OFF = 6
COMMAND_FIRMWARE_RECEIVE = 7
COMMAND_FIRMWARE_FRAME = 8
COMMAND_FIRMWARE_APPLY = 9

#define COMMAND_BACKLIGHT_READ 0
#define COMMAND_BACKLIGHT_SET_EFFECT 1
#define COMMAND_BACKLIGHT_SET_EFFECT_DATA 2
#define COMMAND_BACKLIGHT_SET_COLOR 3
#define COMMAND_BACKLIGHT_SET_WHITE 4
#define COMMAND_BACKLIGHT_SET_BRIGHTNESS 5
#define COMMAND_BACKLIGHT_TURN_OFF 6